package main.java.metier;

/**
 * ClassementHtml generated by hbm2java
 */
public class ClassementHtml
    implements java.io.Serializable
{

    private Integer idClassement;
    private Classement classement;
    private String html;

    public ClassementHtml()
    {
    }

    public ClassementHtml(String html)
    {
        this.html = html;
    }

    public Integer getIdClassement()
    {
        return this.idClassement;
    }

    public void setIdClassement(Integer idClassement)
    {
        this.idClassement = idClassement;
    }

    public String getHtml()
    {
        return this.html;
    }

    public void setHtml(String html)
    {
        this.html = html;
    }

    public Classement getClassement()
    {
        return classement;
    }

    public void setClassement(Classement classement)
    {
        this.classement = classement;
    }
}
