package main.java.metier;

import java.util.Date;

/**
 * Classement generated by hbm2java
 */
public class ClassementEquipe
    implements java.io.Serializable
{

    private Integer idClassement;

    private String rang;
    private String logo;
    private String nomEquipe;
    private String points;
    private String matchJoue;
    private String premierePlace;
    private String deuxiemePlace;
    private String troisiemePlace;
    private String forfait;
    private String nbPeriode;
    private String espritSportif;
    private String html;
    private Classement classement;

    public ClassementEquipe(String rang, String logo, String nomEquipe, String points, String matchJoue, String premierePlace, String deuxiemePlace, String troisiemePlace, String forfait, String nbPeriode, String espritSportif) {
        this.rang = rang;
        this.logo = logo;
        this.nomEquipe = nomEquipe;
        this.points = points;
        this.matchJoue = matchJoue;
        this.premierePlace = premierePlace;
        this.deuxiemePlace = deuxiemePlace;
        this.troisiemePlace = troisiemePlace;
        this.forfait = forfait;
        this.nbPeriode = nbPeriode;
        this.espritSportif = espritSportif;
    }

    public Integer getIdClassement() {
        return idClassement;
    }

    public void setIdClassement(Integer idClassement) {
        this.idClassement = idClassement;
    }

    public String getRang() {
        return rang;
    }

    public void setRang(String rang) {
        this.rang = rang;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getNomEquipe() {
        return nomEquipe;
    }

    public void setNomEquipe(String nomEquipe) {
        this.nomEquipe = nomEquipe;
    }

    public String getPoints() {
        return points;
    }

    public void setPoints(String points) {
        this.points = points;
    }

    public String getMatchJoue() {
        return matchJoue;
    }

    public void setMatchJoue(String matchJoue) {
        this.matchJoue = matchJoue;
    }

    public String getPremierePlace() {
        return premierePlace;
    }

    public void setPremierePlace(String premierePlace) {
        this.premierePlace = premierePlace;
    }

    public String getDeuxiemePlace() {
        return deuxiemePlace;
    }

    public void setDeuxiemePlace(String deuxiemePlace) {
        this.deuxiemePlace = deuxiemePlace;
    }

    public String getTroisiemePlace() {
        return troisiemePlace;
    }

    public void setTroisiemePlace(String troisiemePlace) {
        this.troisiemePlace = troisiemePlace;
    }

    public String getForfait() {
        return forfait;
    }

    public void setForfait(String forfait) {
        this.forfait = forfait;
    }

    public String getNbPeriode() {
        return nbPeriode;
    }

    public void setNbPeriode(String nbPeriode) {
        this.nbPeriode = nbPeriode;
    }

    public String getEspritSportif() {
        return espritSportif;
    }

    public void setEspritSportif(String espritSportif) {
        this.espritSportif = espritSportif;
    }

    public String getHtml() {
        return html;
    }

    public void setHtml(String html) {
        this.html = html;
    }

    public Classement getClassement() {
        return classement;
    }

    public void setClassement(Classement classement) {
        this.classement = classement;
    }
}
