package main.java.metier;

import java.util.Date;
import java.util.List;

/**
 * ClassementHtml generated by hbm2java
 */
public class Classement
    implements java.io.Serializable
{

    private Integer idClassement;
    private String division;
    private String sexe;
    private Date date;
    private List<ClassementEquipe> classementEquipes;
    private String html;

    public Classement()
    {
    }

    public Classement(String division, List<ClassementEquipe> classementEquipes) {
        this.division = division;
        this.classementEquipes = classementEquipes;
    }

    public Classement(String division, String sexe, Date date, List<ClassementEquipe> classementEquipes) {
        this.division = division;
        this.sexe = sexe;
        this.date = date;
        this.classementEquipes = classementEquipes;
    }

    public Integer getIdClassement() {
        return idClassement;
    }

    public void setIdClassement(Integer idClassement) {
        this.idClassement = idClassement;
    }

    public String getDivision() {
        return division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    public String getSexe() {
        return sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public List<ClassementEquipe> getClassementEquipes() {
        return classementEquipes;
    }

    public void setClassementEquipes(List<ClassementEquipe> classementEquipes) {
        this.classementEquipes = classementEquipes;
    }

    public String getHtml() {
        return html;
    }

    public void setHtml(String html) {
        this.html = html;
    }

    @Override
    public String toString() {
        return  division + " - "   + sexe  ;
    }
}
