package main.java.metier;

import java.util.Date;

/**
 * Classement generated by hbm2java
 */
public class Classement
    implements java.io.Serializable
{

    private Integer idClassement;
    private String division;
    private char sexe;
    private Date date;
    private int rang;
    private String logo;
    private String nomEquipe;
    private int points;
    private int matchJoue;
    private int premierePlace;
    private int deuxiemePlace;
    private int troisiemePlace;
    private int forfait;
    private int nbPeriode;
    private int espritSportif;

    private ClassementHtml classementHtml;

    public Classement()
    {
    }

    public Classement(String division, char sexe, Date date, int rang,
                      String logo, String nomEquipe, int points, int matchJoue,
                      int premierePlace, int deuxiemePlace, int troisiemePlace,
                      int forfait, int nbPeriode, int espritSportif)
    {
        this.division = division;
        this.sexe = sexe;
        this.date = date;
        this.rang = rang;
        this.logo = logo;
        this.nomEquipe = nomEquipe;
        this.points = points;
        this.matchJoue = matchJoue;
        this.premierePlace = premierePlace;
        this.deuxiemePlace = deuxiemePlace;
        this.troisiemePlace = troisiemePlace;
        this.forfait = forfait;
        this.nbPeriode = nbPeriode;
        this.espritSportif = espritSportif;
    }

    public Integer getIdClassement()
    {
        return this.idClassement;
    }

    public void setIdClassement(Integer idClassement)
    {
        this.idClassement = idClassement;
    }

    public String getDivision()
    {
        return this.division;
    }

    public void setDivision(String division)
    {
        this.division = division;
    }

    public char getSexe()
    {
        return this.sexe;
    }

    public void setSexe(char sexe)
    {
        this.sexe = sexe;
    }

    public Date getDate()
    {
        return this.date;
    }

    public void setDate(Date date)
    {
        this.date = date;
    }

    public int getRang()
    {
        return this.rang;
    }

    public void setRang(int rang)
    {
        this.rang = rang;
    }

    public String getLogo()
    {
        return this.logo;
    }

    public void setLogo(String logo)
    {
        this.logo = logo;
    }

    public String getNomEquipe()
    {
        return this.nomEquipe;
    }

    public void setNomEquipe(String nomEquipe)
    {
        this.nomEquipe = nomEquipe;
    }

    public int getPoints()
    {
        return this.points;
    }

    public void setPoints(int points)
    {
        this.points = points;
    }

    public int getMatchJoue()
    {
        return this.matchJoue;
    }

    public void setMatchJoue(int matchJoue)
    {
        this.matchJoue = matchJoue;
    }

    public int getPremierePlace()
    {
        return this.premierePlace;
    }

    public void setPremierePlace(int premierePlace)
    {
        this.premierePlace = premierePlace;
    }

    public int getDeuxiemePlace()
    {
        return this.deuxiemePlace;
    }

    public void setDeuxiemePlace(int deuxiemePlace)
    {
        this.deuxiemePlace = deuxiemePlace;
    }

    public int getTroisiemePlace()
    {
        return this.troisiemePlace;
    }

    public void setTroisiemePlace(int troisiemePlace)
    {
        this.troisiemePlace = troisiemePlace;
    }

    public int getForfait()
    {
        return this.forfait;
    }

    public void setForfait(int forfait)
    {
        this.forfait = forfait;
    }

    public int getNbPeriode()
    {
        return this.nbPeriode;
    }

    public void setNbPeriode(int nbPeriode)
    {
        this.nbPeriode = nbPeriode;
    }

    public int getEspritSportif()
    {
        return this.espritSportif;
    }

    public void setEspritSportif(int espritSportif)
    {
        this.espritSportif = espritSportif;
    }

    public ClassementHtml getClassementHtml()
    {
        return classementHtml;
    }

    public void setClassementHtml(ClassementHtml classementHtml)
    {
        this.classementHtml = classementHtml;
    }
}
