package main.java.metier;


/**
 * Match generated by hbm2java
 */
public class Match
    implements java.io.Serializable
{

    private Integer id;
    private String idMatch;
    private MatchEquipe bleu;
    private MatchEquipe gris;
    private MatchEquipe noir;
    private String arbitreChef;
    private String arbitreAdjoint;
    private String html;


    public Match()
    {
    }

    public Match(String idMatch, MatchEquipe bleu, MatchEquipe gris, MatchEquipe noir,
                 String arbitreChef, String arbitreAdjoint)
    {
        this.idMatch = idMatch;
        this.bleu = bleu;
        this.gris = gris;
        this.noir = noir;
        this.arbitreChef = arbitreChef;
        this.arbitreAdjoint = arbitreAdjoint;
    }

    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public String getIdMatch()
    {
        return this.idMatch;
    }

    public void setIdMatch(String idMatch)
    {
        this.idMatch = idMatch;
    }

    public MatchEquipe getBleu()
    {
        return this.bleu;
    }

    public void setBleu(MatchEquipe bleu)
    {
        this.bleu = bleu;
    }

    public MatchEquipe getGris()
    {
        return this.gris;
    }

    public void setGris(MatchEquipe gris)
    {
        this.gris = gris;
    }

    public MatchEquipe getNoir()
    {
        return this.noir;
    }

    public void setNoir(MatchEquipe noir)
    {
        this.noir = noir;
    }

    public String getArbitreChef()
    {
        return this.arbitreChef;
    }

    public void setArbitreChef(String arbitreChef)
    {
        this.arbitreChef = arbitreChef;
    }

    public String getArbitreAdjoint()
    {
        return this.arbitreAdjoint;
    }

    public void setArbitreAdjoint(String arbitreAdjoint)
    {
        this.arbitreAdjoint = arbitreAdjoint;
    }

    public String getHtml()
    {
        return this.html;
    }

    public void setHtml(String html)
    {
        this.html = html;
    }
}
