package main.java.metier;
// default package
// Generated 24 juin 2014 21:13:39 by Hibernate Tools 3.4.0.CR1

/**
 * Equipe generated by hbm2java
 */
public class MatchEquipe
    implements java.io.Serializable
{

    private Integer idEquipe;
    private String color;
    private String nomEquipe;
    private boolean isForfait;
    private String p1;
    private String p2;
    private String p3;
    private String p4;
    private String p5;
    private String p6;
    private String p7;
    private String prol1;
    private String prol2;
    private String prol3;
    private String prol4;
    private String prol5;
    private String prol6;
    private String prol7;
    private String prolDeuxieme;
    private String nbPeriode;
    private String espritSportif;
    private String points;
    private Match match;

    public MatchEquipe()
    {
    }


    public Integer getIdEquipe()
    {
        return this.idEquipe;
    }

    public void setIdEquipe(Integer idEquipe)
    {
        this.idEquipe = idEquipe;
    }

    public String getColor()
    {
        return this.color;
    }

    public void setColor(String color)
    {
        this.color = color;
    }

    public String getNomEquipe()
    {
        return this.nomEquipe;
    }

    public void setNomEquipe(String nomEquipe)
    {
        this.nomEquipe = nomEquipe;
    }

    public boolean isForfait()
    {
        return this.isForfait;
    }

    public void setForfait(boolean isForfait)
    {
        this.isForfait = isForfait;
    }

    public String getP1()
    {
        return this.p1;
    }

    public void setP1(String p1)
    {
        this.p1 = p1;
    }

    public String getP2()
    {
        return this.p2;
    }

    public void setP2(String p2)
    {
        this.p2 = p2;
    }

    public String getP3()
    {
        return this.p3;
    }

    public void setP3(String p3)
    {
        this.p3 = p3;
    }

    public String getP4()
    {
        return this.p4;
    }

    public void setP4(String p4)
    {
        this.p4 = p4;
    }

    public String getP5()
    {
        return this.p5;
    }

    public void setP5(String p5)
    {
        this.p5 = p5;
    }

    public String getP6()
    {
        return this.p6;
    }

    public void setP6(String p6)
    {
        this.p6 = p6;
    }

    public String getP7()
    {
        return this.p7;
    }

    public void setP7(String p7)
    {
        this.p7 = p7;
    }

    public String getProl1()
    {
        return this.prol1;
    }

    public void setProl1(String prol1)
    {
        this.prol1 = prol1;
    }

    public String getProl2()
    {
        return this.prol2;
    }

    public void setProl2(String prol2)
    {
        this.prol2 = prol2;
    }

    public String getProl3()
    {
        return this.prol3;
    }

    public void setProl3(String prol3)
    {
        this.prol3 = prol3;
    }

    public String getProl4()
    {
        return this.prol4;
    }

    public void setProl4(String prol4)
    {
        this.prol4 = prol4;
    }

    public String getProl5()
    {
        return this.prol5;
    }

    public void setProl5(String prol5)
    {
        this.prol5 = prol5;
    }

    public String getProl6()
    {
        return this.prol6;
    }

    public void setProl6(String prol6)
    {
        this.prol6 = prol6;
    }

    public String getProl7()
    {
        return this.prol7;
    }

    public void setProl7(String prol7)
    {
        this.prol7 = prol7;
    }

    public String getProlDeuxieme()
    {
        return this.prolDeuxieme;
    }

    public void setProlDeuxieme(String prolDeuxieme)
    {
        this.prolDeuxieme = prolDeuxieme;
    }

    public String getNbPeriode()
    {
        return this.nbPeriode;
    }

    public void setNbPeriode(String nbPeriode)
    {
        this.nbPeriode = nbPeriode;
    }

    public String getEspritSportif()
    {
        return this.espritSportif;
    }

    public void setEspritSportif(String espritSportif)
    {
        this.espritSportif = espritSportif;
    }

    public String getPoints()
    {
        return this.points;
    }

    public void setPoints(String points)
    {
        this.points = points;
    }

    public Match getMatch()
    {
        return match;
    }

    public void setMatch(Match match)
    {
        this.match = match;
    }

}
