package main.java.metier;

/**
 * Match generated by hbm2java
 */
public class Match
    implements java.io.Serializable
{

    private Integer id;
    private String idMatch;
    private Equipe bleu;
    private Equipe gris;
    private Equipe noir;
    private String arbitreChef;
    private String arbitreAdjoint;

    private MatchHtml matchHtml;

    public Match()
    {
    }

    public Match(String idMatch, Equipe bleu, Equipe gris, Equipe noir,
                 String arbitreChef, String arbitreAdjoint)
    {
        this.idMatch = idMatch;
        this.bleu = bleu;
        this.gris = gris;
        this.noir = noir;
        this.arbitreChef = arbitreChef;
        this.arbitreAdjoint = arbitreAdjoint;
    }

    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public String getIdMatch()
    {
        return this.idMatch;
    }

    public void setIdMatch(String idMatch)
    {
        this.idMatch = idMatch;
    }

    public Equipe getBleu()
    {
        return this.bleu;
    }

    public void setBleu(Equipe bleu)
    {
        this.bleu = bleu;
    }

    public Equipe getGris()
    {
        return this.gris;
    }

    public void setGris(Equipe gris)
    {
        this.gris = gris;
    }

    public Equipe getNoir()
    {
        return this.noir;
    }

    public void setNoir(Equipe noir)
    {
        this.noir = noir;
    }

    public String getArbitreChef()
    {
        return this.arbitreChef;
    }

    public void setArbitreChef(String arbitreChef)
    {
        this.arbitreChef = arbitreChef;
    }

    public String getArbitreAdjoint()
    {
        return this.arbitreAdjoint;
    }

    public void setArbitreAdjoint(String arbitreAdjoint)
    {
        this.arbitreAdjoint = arbitreAdjoint;
    }

    public MatchHtml getMatchHtml()
    {
        return matchHtml;
    }

    public void setMatchHtml(MatchHtml matchHtml)
    {
        this.matchHtml = matchHtml;
    }
}
